import { StyleSheet } from '@/v2/aphrodite';

const styles = StyleSheet.create({
  markColorPickerName: {
    display: 'inline-block',
    verticalAlign: 'middle',
    paddingLeft: '20px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  markColorPickerWrap: {
    display: 'inline-flex',
    position: 'relative',
    outline: 'none',
  },
  markColorPickerInfo: { cursor: 'pointer' },
  markColorPickerColor: {
    display: 'inline-block',
    width: '60px',
    height: '20px',
    verticalAlign: 'middle',
    backgroundPosition: 'center',
    backgroundSize: 'contain',
    backgroundRepeat: 'no-repeat',
  },
  markColorPickerItem: {
    display: 'flex',
    alignItems: 'center',
    overflow: 'hidden',
  },
  markColorPickerItemText: {
    fontSize: '16px',
    fontFamily: ['GilroyRegular', 'sans-serif'],
    paddingLeft: '20px',
  },
  markColorPickerButton: {
    color: '#C2C3C8',
    fontSize: '14px',
    fontFamily: ['GilroyRegular', 'sans-serif'],
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: '10px',
    paddingBottom: '10px',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    border: 'none',
    transition: 'background-color .3s ease-out, color .3s ease-out',
    position: 'relative',
    outline: 'none',
    ':after': {
      position: 'absolute',
      content: '\'\'',
      left: 0,
      right: 0,
      top: 0,
      height: '1px',
      backgroundColor: '#F1F2F6',
    },
    ':hover': {
      backgroundColor: '#F3F3F3',
      color: '#6F6F6F',
    },
  },
  comboBoxDropdown: {
    content: '\'\'',
    position: 'absolute',
    margin: 0,
    padding: 0,
    left: 0,
    top: 'calc(100% + 20px)',
    backgroundColor: '#ffffff',
    minWidth: '100%',
    boxSizing: 'border-box',
    boxShadow: '0px 8px 10px rgba(0, 0, 0, 0.12)',
    border: '2px solid #DDE2EF',
    zIndex: 10,
  },
  comboBoxDropdownActive: { display: 'block' },
  comboBoxDropdownWrapper: {
    maxHeight: '270px',
    overflowY: 'auto',
    overflowX: 'hidden',
    position: 'relative',
  },
  comboBoxDropdownItem: {
    listStyle: 'none',
    lineHeight: '1.3em',
    color: '#1f1f1f',
    fontFamily: 'GilroyRegular',
    fontSize: '18px',
    padding: '16px 20px',
    maxWidth: '100%',
    overflowX: 'hidden',
    whiteSpace: 'nowrap',
    ':hover': {
      backgroundColor: '#f5f5f5',
      cursor: 'pointer',
    },
  },
  comboBoxDropdownItemPadding10: { padding: '10px' },
});

export default styles;
